apiVersion: v1
kind: Service
metadata:
  name: simple-app-service
  labels:
    app:  simple-app
spec:
  selector:
    name: simple-app
  type: LoadBalancer
  ports:
    - port: 7000
      targetPort: 5000
      nodePort: 30001