apiVersion: v1
kind: Pod
metadata:
  name: simple-app
  labels:
    app:  simple-app
spec:
  containers:
  - name: simple-app-con
    image: pranavv481/simple-app
    ports:
    - containerPort: 5000
